
title: AdBlockify
description: A simple AdBlocker for all your ad blocking needs that respects your privacy.
show_downloads: true
theme: jekyll-theme-cayman
github:
  zip_url: https://github.com/TamoghnaK13/AdBlockify/download.zip
  another_url: another value
